"""
Program: constants.py
Author: Nick Hofmann | nickhofmann1989@hotmail.com | nohofmann@dmacc.edu
Last Modified: 6/10/2020

Program specifications: This is the that I'm using for constants. I will import it into
coupon_calculations.py
"""
# SALES TAX PERCENTAGE CONSTANT
SALES_TAX_RATE = 1.06
# CASH COUPON CONSTANTS
CASH_COUPON_5 = 5
CASH_COUPON_10 = 10
# PERCENT COUPON CONSTANTS
PERCENT_COUPON_10 = .9
PERCENT_COUPON_15 = .85
PERCENT_COUPON_20 = .80
# SHIPPING CHARGE CONSTANTS
UNDER_10_SHIPPING = 5.95
BETWEEN_10_TO_30_SHIPPING = 7.95
BETWEEN_30_TO_50_SHIPPING = 11.95
OVER_50_SHIPPING = 0
# PRICE THRESHOLD CONSTANTS
TEN_DOLLAR_THRESHOLD = 10
THIRTY_DOLLAR_THRESHOLD = 30
FIFTY_DOLLAR_THRESHOLD = 50
